# get the header files for the lance project
#
# Tom Trebisky 5/23/2025

ROM = /Projects/sun3-prom/Github

# We could just copy everything, but I wanted to,
#  by trial and error, just copy what was actually
#  required

get:
	cp $(ROM)/dev/saio.h .
	cp $(ROM)/h/param.h .
	cp $(ROM)/h/socket.h .
	cp $(ROM)/dev/if_lereg.h .
	cp $(ROM)/dev/if.h .
	cp $(ROM)/h/in.h .
	cp $(ROM)/dev/if_ether.h .
	cp $(ROM)/h/idprom.h .
	cp $(ROM)/sun3/cpu.map.h .
	cp $(ROM)/sun3/cpu.addrs.h .
	cp $(ROM)/h/pixrect.h .
	cp $(ROM)/h/protos.h .
	cp $(ROM)/h/types.h .
	cp $(ROM)/h/systypes.h .
	cp $(ROM)/h/sunromvec.h .
	cp $(ROM)/h/in_systm.h .
	cp $(ROM)/h/ip.h .
	cp $(ROM)/h/udp.h .
	cp $(ROM)/h/sainet.h .
	cp $(ROM)/h/tftp.h .

# THE END
